### ISSUE TITLE
"Final vector tiles" has two features with the same ID

### ISSUE THREAD

**Issue by lbud** [mapbox/vector-tiles#10]
![image](https://cloud.githubusercontent.com/assets/3170312/14871671/5b74f85e-0c99-11e6-8dc7-4a19d2a85bff.png)

Both of these say `id: 1` — these should be unique I think?
(Also, the second one is missing a colon after `features`, inconsistent with other objects here)

cc @mapsam

**Comment by mapsam** [comment]
Good eyes @lbud! The duplicate ID is from the example in the spec. Maybe @flippmoke can confirm or deny how this should work. The [spec does say that `id` should be unique](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features).

@flippmoke if the `id`s need updating, I can update in both places.

**Comment by flippmoke** [comment]
https://github.com/mapbox/vector-tile-spec/issues/60

**Comment by mapsam** [comment]
Thanks @flippmoke - I made a [PR for that fix](https://github.com/mapbox/vector-tile-spec/pull/74), and we can update here as well.
