### ISSUE TITLE
Minor error in copy

### ISSUE THREAD

**Issue by ajithranka** [mapbox/vector-tiles#16]
I was reading through the [specification page](https://www.mapbox.com/vector-tiles/specification/) and found this error:

![screen shot 2016-06-13 at 11 38 28 am](https://cloud.githubusercontent.com/assets/11095038/15998438/fc8f23cc-315b-11e6-8948-abb2cc52a685.png)

The text should say "vector tile to the right" instead of left.

**Comment by mapsam** [comment]
Thanks for finding this @ajithranka! Fixed in 8ced5a4b788448d0e57cd08aa722266f61cda818
