### ISSUE TITLE
Markdown not being interpreted correctly

### ISSUE THREAD

**Issue by ajashton** [mapbox/vector-tiles#2]
There are some markdown issues in the vector tile services docs:

![](http://i.imgur.com/DFjy21p.png)

It should look like this:

![](http://i.imgur.com/vQuFqLO.png)

The previous versions of these pages were rendered with rdiscount (`markdown: rdiscount` in _config.yml). I tested adding that setting to this repo but it broke the templating (no footer on any pages, no TOC on the spec page). It should be possible to make it work (the main mapbox.com site uses rdiscount) but maybe it would just be easier to convert that markdown to html ourselves in the docs source.

cc @mapsam

**Comment by mapsam** [comment]
Good catch @ajashton - this is a regression that I should have caught. Will take a look now!
