### ISSUE TITLE
Link Protobuf style guide

### ISSUE THREAD

**Issue by mikemorris** [mapbox/vector-tiles#4]
Mentioned in https://github.com/mapbox/vector-tiles/blob/mb-pages/_posts/spec/0001-01-02-versioning.md, would love a link!

**Comment by mapsam** [comment]
We can definitely add a link! Are you thinking something like "The fields within the [protobuffer](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto) are more clearly defined" @mikemorris?

**Comment by mikemorris** [comment]
> 1.0.1 | July 28, 2014 | Update .proto file to match Protobuf style guide, changed namespace

I was thinking from the way this was phrased there was like some Google document recommending how to structure PBF specs or something. Our VT proto is already linked in the next paragraph I think.

**Comment by mapsam** [comment]
No, there totally should be a link for that! The spec changelog references https://github.com/mapbox/vector-tile-spec/issues/3

I'll add it

**Comment by mapsam** [comment]
@mikemorris all 👍 now
