### ISSUE TITLE
Tilequery API returning incomplete results

### ISSUE THREAD

**Issue by andycalder** [mapbox/vector-tiles#49]
I have a vector tileset containing 67 LineString features within a radius of ~10km. If I use the following request per the [API](https://www.mapbox.com/api-documentation/#retrieve-features-from-vector-tiles):

`https://api.mapbox.com/v4/andycalder.cj51y5ioi09wh32p1s9frlt9l-30bnb/tilequery/-122.954516,50.112784.json?radius=10000&limit=50&access_token={}`

I get a json containing only 7 features. I understand the API will limit the number of returned features to 50 but I’m getting nowhere near that number. The documentation says:

> Due to the nature of tile buffering, a query with a large radius made against equally large point or line data may not include all possible features in the results.

Could this be the cause of my problem?

**Comment by mapsam** [comment]
Hi @andycalder since this is specific to Mapbox APIs and the tools used by the Tilequery API, I recommend reaching out to help@mapbox.com!

**Comment by andycalder** [comment]
Will do, thanks!
