### ISSUE TITLE
Update v5 and v6 update schedules

### ISSUE THREAD

**Issue by 1ec5** [mapbox/vector-tiles#51]
Streets source v5 and v6 documentation currently claim that these tilesets receive regular updates from OpenStreetMap but suggest upgrading to v7. These documents should suggest v8 instead once it’s available.

https://github.com/mapbox/vector-tiles/blob/a0e3a85f4525424bdb2e4a4200efe93ff5fcdac3/_posts/services/0001-02-20-mapbox-streets-v5.md#L48
https://github.com/mapbox/vector-tiles/blob/a0e3a85f4525424bdb2e4a4200efe93ff5fcdac3/_posts/services/0001-02-19-mapbox-streets-v6.md#L128

/cc @ajashton @colleenmcginnis @captainbarbosa

**Comment by colleenmcginnis** [comment]
This was done in #75 🎉
