### ISSUE TITLE
Update v8 documentation formatting

### ISSUE THREAD

**Issue by hjudge** [mapbox/vector-tiles#53]
The documentation formatting for Layer Reference at https://www.mapbox.com/vector-tiles/mapbox-streets-v8/#layer-reference is wonky: 

![screen shot 2018-06-12 at 2 47 30 pm](https://user-images.githubusercontent.com/10069374/41319107-973296d4-6e4f-11e8-8e4f-16a0b5d87c21.png)

**Comment by colleenmcginnis** [comment]
cc @ajashton

**Comment by ajashton** [comment]
Woops, "Best viewed in ~Netscape Navigator~ Firefox." On it.
