### ISSUE TITLE
Broken image in Streets source v7 reference

### ISSUE THREAD

**Issue by 1ec5** [mapbox/vector-tiles#60]
There’s a broken image in the Streets source v7 reference that’s supposed to show a Studio screenshot:

https://github.com/mapbox/vector-tiles/blob/a88bd062b6ab1429dda5e7502a03071dbbaac6fb/_posts/services/0001-02-18-mapbox-streets-v7.md#L107

Looks like the image has been removed from the v8 reference.

/cc @HeyStenson

**Comment by HeyStenson** [comment]
This was resolved in #61 🎉
