### ISSUE TITLE
Explicitly highlight keys and values

### ISSUE THREAD

**Issue by mapsam** [mapbox/vector-tiles#8]
The `keys` and `values` in the protobuf file are ordered in a way where their "count" resets when being referenced by the `tags` above. It would be helpful to highlight the full list of `keys` and `values` so the tags count (i.e. `tags: 1`) is clearer. 

cc @lbud

**Comment by mapsam** [comment]
@lbud which do you like best here?

Border left
<img width="511" alt="screen shot 2016-04-27 at 4 09 20 pm" src="https://cloud.githubusercontent.com/assets/1943001/14870899/78e72274-0c92-11e6-930d-36e6e5bc7796.png">

Counts
<img width="568" alt="screen shot 2016-04-27 at 4 18 42 pm" src="https://cloud.githubusercontent.com/assets/1943001/14871059/c342c138-0c93-11e6-8607-80f04f02f6de.png">

Both
<img width="585" alt="screen shot 2016-04-27 at 4 19 26 pm" src="https://cloud.githubusercontent.com/assets/1943001/14871076/d658678c-0c93-11e6-8b22-f4948f12f17c.png">

**Comment by lbud** [comment]
👀 ooooOo.
I kind of want to say both…?

**Comment by mapsam** [comment]
both it is!
